#!/usr/bin/env bash

# This script transfers a file from the client to a server using scp.

# Check if the correct number of arguments is provided
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Assign command-line arguments to variables
  filepath=$1
  server_ip=$2
  username=$3
  ssh_key=$4

  # Use scp to transfer the file to the server
  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$filepath" "$username@$server_ip:~"
  
fi
