#!/usr/bin/env bash

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Create a directory for Nginx configuration
mkdir /etc/nginx/html

# Create a sample HTML page
echo "Hello World!" > /etc/nginx/html/index.html

# Create a server block configuration for Nginx
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /etc/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
}
" > /etc/nginx/sites-available/default

# Restart Nginx to apply the new configuration
nginx -s reload
