#!/usr/bin/env bash
# Installs Nginx with the specified settings:
# Listens on port 80.
# Responds with a page displaying "Hello World" 
# when accessed with a curl GET request at the root.

# Install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# configure nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Create a sample HTML page
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply the new configuration
nginx -s start
