#!/usr/bin/env bash
# This script installs Nginx with the following configurations:
#    1. Nginx listens on port 80.
#    2. When queried at the root with a curl GET request, it returns a page containing "Ceci n'est pas une page."

# Install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Restart Nginx to apply the changes
service nginx restart

