#!/usr/bin/env bash
# Install and configure Nginx to have a custom 404 page with the string "Ceci n'est pas une page"

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a Sample Page
echo "Hello World!" > /var/www/html/index.html

# Add the following configuration to the existing server block for redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com\/ permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure error page and redirect error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

