#!/usr/bin/env bash
# This script defined OSI Model as The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technology and its 7 layers are arranged from lowest to highest

2
2
