#!/usr/bin/env bash
# The script that pings an IP address passed as an argument

# an IP variable
IP="${1}"

fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi

