#!/usr/bin/env bash
# Copy the default Nginx site configuration to the sites-enabled directory
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sudo pkill -o nginx
